
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        cluster-name: HZ
        enabled: true
    loadbalancer:
      nacos:
        enabled: true
    sentinel:
      transport:
        dashboard: localhost:8080

feign:
  sentinel:
    enabled: true

mybatis:
  type-aliases-package: com.example.orderservice.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




