eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://app1:8101/eureka/,http://app2:8102/eureka/
server:
  port: 8301

spring:
  application:
    name: sping-cloud-consumer
feign:
  hystrix:
    enabled: true
consumer:
  name: mali
